export const STAFF_LOADING='STAFF_LOADING';
export const ADD_STAFF='ADD_LOADING';
export const FAILED_STAFF='FAILED_STAFF';

export const DEPART_LOADING='DEPART_LOADING';
export const ADD_DEPART='ADD_DEPART';
export const FAILED_DEPART='FAILED_DEPART';